[package]
name = "find_workspace_packages"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types = { path = "../types" }
regex = "1.5.4"
lazy_static = "1.4.0"
glob = "0.3.0"
anyhow = "1.0.53"
globset = "0.4.8"
read_project_manifest = { path = "../read_project_manifest" }