[package]
name = "lockfile_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
constants = { path = "../constants" }
types = { path = "../types" }
tokio = { version = "1.16.1", features = ["fs"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_yaml = "0.8"
regex = "1.5.4"
semver = "1.0.4"
itertools = "0.10.3"
tempfile = "3.3.0"
anyhow = "1.0.53"
strip_bom = "1.0.0"
lazy_static = "1.4.0"
rayon = "1.5.1"

[dev-dependencies]
assert_matches = "1.5"