[package]
name = "lockfile_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types = { path = "../types" }
tokio = { version = "1.16.1", features = ["fs"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_yaml = "0.8"
regex = "1.5.4"
semver = "1.0.4"
itertools = "0.10.3"