[package]
name = "lockfile_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lockfile_types = { path = "../lockfile_types" }
types = { path = "../types" }