[package]
name = "parse_wanted_dependency"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
validate_npm_package_name = { path = "../validate_npm_package_name" }