[package]
name = "store_connection_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
store_path = { path = "../store_path" }
anyhow = "1.0.53"
serde_json = "1.0.78"
serde = { version = "1.0", features = ["derive"] }
log = "0.4.14"
store_controller_types = { path = "../store_controller_types" }