[package]
name = "store_path"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
anyhow = "1.0.53"
dirs = "4.0.0"
relative-path = "1.6.0"