[package]
name = "read_project_manifest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types = { path = "../types" }
strip_bom = "1.0.0"
anyhow = "1.0.53"
json5 = "0.4.1"
serde_yaml = "0.8"
serde_json = "1.0.78"
tempfile = "3.3.0"
temp_path = { path = "../temp_path" }
lazy_static = "1.4.0"

[dev-dependencies]
assert_matches = "1.5"
pretty_assertions = "1.0.0"