[package]
name = "hosted_git_info"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
urlencoding = "2.1.0"
lru = "0.7.2"
lazy_static = "1.4.0"
regex = "1.5.4"
url = "2.2.2"
pretty_assertions = "1.0.0"