[package]
name = "resolvers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types = { path = "../types" }
regex = "1.5.4"
ssri = "7.0.0"
lazy_static = "1.4.0"
dirs = "4.0.0"
relative-path = "1.6.0"
strip_bom = "1.0.0"
anyhow = "1.0.53"
json5 = "0.4.1"
serde_yaml = "0.8"
serde_json = "1.0.78"
tempfile = "3.3.0"
read_project_manifest = { path = "../read_project_manifest" }
hosted_git_info = { path = "../hosted_git_info" }